FROM pidgin/release-builder:release-2.x.y AS build

COPY . /pidgin

RUN set -ex && \
	cd /pidgin && \
	./autogen.sh --enable-debug && \
	make -s -j$(nproc) docs

FROM rwgrim/goserve

EXPOSE 3000

COPY --from=build /pidgin/doc/html html

